name: nxv
channels:
  - conda-forge
  - mantid
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - pycifrw
  - h5py
  - pyvista>=0.34.2
  - pyvistaqt
  - pytest
  - mantidworkbench
  - scikit-learn
  - scikit-image
## needs to install pyqtdarktheme, with pip : pip install pyqtdarktheme
